const ORDER_STATUS = {
  NEW: 'NEW',
  CONFIRMED: 'CONFIRMED',
  IN_PRODUCTION: 'IN_PRODUCTION',
  PRODUCED: 'PRODUCED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERING: 'DELIVERING',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID'
};

const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  CUSTOMER: 'CUSTOMER',
  PRODUCTION_ENGINEER: 'PRODUCTION_ENGINEER',
  DRIVER: 'DRIVER',
  ACCOUNTANT: 'ACCOUNTANT'
};

module.exports = { ORDER_STATUS, PAYMENT_STATUS, ROLES };
